default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: web_resume

test:
  <<: *default
  database: web_resume_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
